// actionTypes.js
export const PERFORMANCE_LIST_REQUEST = "PERFORMANCE_LIST_REQUEST"
export const PERFORMANCE_LIST_SUCCESS = "PERFORMANCE_LIST_SUCCESS"
export const PERFORMANCE_LIST_FAIL = "PERFORMANCE_LIST_FAIL"

export const ADD_PERFORMANCE_REQUEST = "ADD_PERFORMANCE_REQUEST"
export const ADD_PERFORMANCE_SUCCESS = "ADD_PERFORMANCE_SUCCESS"
export const ADD_PERFORMANCE_FAILURE = "ADD_PERFORMANCE_FAILURE"

export const EDIT_PERFORMANCE_REQUEST = "EDIT_PERFORMANCE_REQUEST"
export const EDIT_PERFORMANCE_SUCCESS = "EDIT_PERFORMANCE_SUCCESS"
export const EDIT_PERFORMANCE_FAILURE = "EDIT_PERFORMANCE_FAILURE"

export const DELETE_PERFORMANCE_REQUEST = "DELETE_PERFORMANCE_REQUEST"
export const DELETE_PERFORMANCE_SUCCESS = "DELETE_PERFORMANCE_SUCCESS"
export const DELETE_PERFORMANCE_FAILURE = "DELETE_PERFORMANCE_FAILURE"
