// roundActionTypes.js
export const ADD_ROUND_REQUEST = "ADD_ROUND_REQUEST"
export const ADD_ROUND_SUCCESS = "ADD_ROUND_SUCCESS"
export const ADD_ROUND_FAILURE = "ADD_ROUND_FAILURE"

export const REMOVE_ACTIVITY_FROM_ROUND_REQUEST = "REMOVE_ACTIVITY_FROM_ROUND_REQUEST"
export const REMOVE_ACTIVITY_FROM_ROUND_SUCCESS = "REMOVE_ACTIVITY_FROM_ROUND_SUCCESS"
export const REMOVE_ACTIVITY_FROM_ROUND_FAILURE = "REMOVE_ACTIVITY_FROM_ROUND_FAILURE"

export const REMOVE_ROUND_REQUEST = "REMOVE_ROUND_REQUEST"
export const REMOVE_ROUND_SUCCESS = "REMOVE_ROUND_SUCCESS"
export const REMOVE_ROUND_FAILURE = "REMOVE_ROUND_FAILURE"
