// actionTypes.js
export const COMPETITION_LIST_REQUEST = "COMPETITION_LIST_REQUEST"
export const COMPETITION_LIST_SUCCESS = "COMPETITION_LIST_SUCCESS"
export const COMPETITION_LIST_FAIL = "COMPETITION_LIST_FAIL"

export const ADD_COMPETITION_REQUEST = "ADD_COMPETITION_REQUEST"
export const ADD_COMPETITION_SUCCESS = "ADD_COMPETITION_SUCCESS"
export const ADD_COMPETITION_FAILURE = "ADD_COMPETITION_FAILURE"

export const EDIT_COMPETITION_REQUEST = "EDIT_COMPETITION_REQUEST"
export const EDIT_COMPETITION_SUCCESS = "EDIT_COMPETITION_SUCCESS"
export const EDIT_COMPETITION_FAILURE = "EDIT_COMPETITION_FAILURE"

export const DELETE_COMPETITION_REQUEST = "DELETE_COMPETITION_REQUEST"
export const DELETE_COMPETITION_SUCCESS = "DELETE_COMPETITION_SUCCESS"
export const DELETE_COMPETITION_FAILURE = "DELETE_COMPETITION_FAILURE"
